repositories:
  packman: true
  codecs: true
  nvidia: true

base_system:
  base_packages: true
  flatpak: true
  printing: true
  wireless: true
  laptop_optimization: true
  nvidia_driver: true
zram:
  #size: "ram"            # <<< NOTEBOOK
  size: "ram / 2"        # <<< DESKTOP
  #size: "ram / 4"        # <<< SERVER
  compression: "zstd"
  priority: 100

desktop:
  #---Verfügbare Desktops---#
  available:
    - xfce
    - gnome
    - kde
  #---Aktiv---#
  environment: xfce

filemanager:
  nautilus: true
  thunar: true
  dolphin: true

calendar:
  gnome-calendar: true
  orage: true
  korganizer: true

editor:
  gnome_text_editor: true
  mousepad: true
  kate: true
  geany: true

image_viewer:
  loupe: true
  ristretto: true
  gwenview: true
  nomacs: true

pdf_viewer:
  papers: true
  okular: true
  evince: true

screenshot_tool:
  xfce4_screenshooter: true
  spectacle: true
  flameshot: true

applications:
  firefox: true               # (war bereits installiert)
  chromium: true
  brave: true
  google_chrome: true
  thunderbird: true           # (war bereits installiert)
  betterbird: true
  geary: true
  signal_desktop: true        # (Repository musste hinzugefügt werden)
  telegram: true
  viber: true
  discord: true
  # Microsoft Teams           # (2023.03.20 Nur noch die PWA ; Weboberfläche)
  zoom: true
  showtime: true
  vlc: true
  celluloid: true
  parole: true
  rhythmbox: true
  musicpod: true
  soundconverter: true
  eyedropper: true
  gcolor3: true
  gimp: true
  krita: true
  kooha: true
  handbrake: true
  kdenlive: true
  openshot: true
  wine: true
  steam: true
  lutris: true
  rustdesk: true
  anydesk: true
  teamviewer: true
  ranger: true
  yazi: true
  zsh: true
  #ghostty: true
  kitty: true
  urxvt: true
  tilix: true
  conky: true
  zim: true
  keepassxc: true
  pycharm: true               # Entwicklungs-IDE
  sublime: true               # (Nutzt die alte 3.x Version)
  weechat: true
  kvm: true
  virtualbox: true
  texlive_latex: true