repositories:
  packman: true
  codecs: true
  nvidia: true

base_system:
  base_packages: true
  flatpak: true
  printing: true
  wireless: true
  laptop_optimization: true
  nvidia_driver: true
zram:
  #size: "ram"            # <<< NOTEBOOK
  size: "ram / 2"        # <<< DESKTOP
  #size: "ram / 4"        # <<< SERVER
  compression: "zstd"
  priority: 100

desktop:
  #---Verfügbare Desktops---#
  available:
    - xfce
    - gnome
    - kde
  #---Aktiv---#
  environment: xfce

filemanager:
  nautilus: true
  thunar: true
  dolphin: true